nodeLinker: node-modules
nmHoistingLimits: workspaces
npmMinimalAgeGate: 1d

npmScopes:
  litlynx:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
