// swift-tools-version: 6.0
// AUTO-SCAFFOLDED by react-native spm scaffold — safe to edit & commit via patch-package.
// AUTO-SCAFFOLDED-VERSION: 19
// Cache slot: 0.87.0/dual-flavor
// Edit the contents below if needed and re-run `npx patch-package <dep-name>`
// to persist across `npm install`. To regenerate from the podspec, remove
// this file (or just this marker) and re-run `npx react-native spm scaffold`.
//
// Package references are plain relative paths, computed when this file was
// scaffolded. They stay correct because the file is re-scaffolded per app
// and cache slot, and any node_modules relayout reinstalls this package
// (dropping the file) anyway.

import PackageDescription

let package = Package(
    name: "ReactNativeEnrichedHtml",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ReactNativeEnrichedHtml", targets: ["ReactNativeEnrichedHtml"]),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "React-GeneratedCode", path: "../../../ios"),
    ],
    targets: [
        .target(
            name: "ReactNativeEnrichedHtml",
            dependencies: [.product(name: "ReactHeaders", package: "ReactNative"), .product(name: "ReactNativeHeaders", package: "ReactNative"), .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"), .product(name: "ReactAppHeaders", package: "React-GeneratedCode")],
            path: ".",
            sources: [
                "cpp/GumboParser/GumboParser.h",
                "cpp/parser/GumboNormalizer.c",
                "cpp/parser/GumboParser.cpp",
                "cpp/parser/GumboParser.hpp",
                "ios/EnrichedTextInputView.h",
                "ios/EnrichedTextInputView.mm",
                "ios/EnrichedTextInputViewManager.mm",
                "ios/EnrichedTextView.h",
                "ios/EnrichedTextView.mm",
                "ios/EnrichedTextViewManager.mm",
                "ios/config/EnrichedConfig.h",
                "ios/config/EnrichedConfig.mm",
                "ios/enrichedInputTextView/EnrichedInputTextView.h",
                "ios/enrichedInputTextView/EnrichedInputTextView.mm",
                "ios/enrichedTextTextView/EnrichedTextTextView.h",
                "ios/enrichedTextTextView/EnrichedTextTextView.mm",
                "ios/extensions/ColorExtension.h",
                "ios/extensions/ColorExtension.mm",
                "ios/extensions/FontExtension.h",
                "ios/extensions/FontExtension.mm",
                "ios/extensions/ImageExtension.h",
                "ios/extensions/ImageExtension.mm",
                "ios/extensions/LayoutManagerExtension.h",
                "ios/extensions/LayoutManagerExtension.mm",
                "ios/extensions/StringExtension.h",
                "ios/extensions/StringExtension.mm",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/ComponentDescriptors.cpp",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/ComponentDescriptors.h",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/EventEmitters.cpp",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/EventEmitters.h",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/Props.cpp",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/Props.h",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/RCTComponentViewHelpers.h",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/ShadowNodes.cpp",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/ShadowNodes.h",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/States.cpp",
                "ios/generated/ReactCodegen/ReactNativeEnrichedSpec/States.h",
                "ios/htmlParser/HtmlParser.h",
                "ios/htmlParser/HtmlParser.mm",
                "ios/inputAttributesManager/InputAttributesManager.h",
                "ios/inputAttributesManager/InputAttributesManager.mm",
                "ios/inputHtmlParser/InputHtmlParser.h",
                "ios/inputHtmlParser/InputHtmlParser.mm",
                "ios/interfaces/AlignmentEntry.h",
                "ios/interfaces/AlignmentEntry.mm",
                "ios/interfaces/AttributeEntry.h",
                "ios/interfaces/AttributeEntry.mm",
                "ios/interfaces/BaseStyleProtocol.h",
                "ios/interfaces/EnrichedTextStyleHeaders.h",
                "ios/interfaces/EnrichedViewHost.h",
                "ios/interfaces/ImageAttachment.h",
                "ios/interfaces/ImageAttachment.mm",
                "ios/interfaces/ImageData.h",
                "ios/interfaces/ImageData.mm",
                "ios/interfaces/LinkData.h",
                "ios/interfaces/LinkData.mm",
                "ios/interfaces/LinkRegexConfig.h",
                "ios/interfaces/LinkRegexConfig.mm",
                "ios/interfaces/MediaAttachment.h",
                "ios/interfaces/MediaAttachment.mm",
                "ios/interfaces/MentionParams.h",
                "ios/interfaces/MentionParams.mm",
                "ios/interfaces/MentionStyleProps.h",
                "ios/interfaces/MentionStyleProps.mm",
                "ios/interfaces/StyleBase.h",
                "ios/interfaces/StyleBase.mm",
                "ios/interfaces/StyleHeaders.h",
                "ios/interfaces/StylePair.h",
                "ios/interfaces/StylePair.mm",
                "ios/interfaces/StyleTypeEnum.h",
                "ios/interfaces/TextDecorationLineEnum.h",
                "ios/interfaces/TextDecorationLineEnum.mm",
                "ios/internals/EnrichedTextComponentDescriptor.h",
                "ios/internals/EnrichedTextInputViewComponentDescriptor.h",
                "ios/internals/EnrichedTextInputViewShadowNode.h",
                "ios/internals/EnrichedTextInputViewShadowNode.mm",
                "ios/internals/EnrichedTextInputViewState.cpp",
                "ios/internals/EnrichedTextInputViewState.h",
                "ios/internals/EnrichedTextViewShadowNode.h",
                "ios/internals/EnrichedTextViewShadowNode.mm",
                "ios/internals/EnrichedTextViewState.cpp",
                "ios/internals/EnrichedTextViewState.h",
                "ios/styles/AlignmentStyle.mm",
                "ios/styles/BlockQuoteStyle.mm",
                "ios/styles/BoldStyle.mm",
                "ios/styles/CheckboxListStyle.mm",
                "ios/styles/CodeBlockStyle.mm",
                "ios/styles/EnrichedTextStyles.mm",
                "ios/styles/H1Style.mm",
                "ios/styles/H2Style.mm",
                "ios/styles/H3Style.mm",
                "ios/styles/H4Style.mm",
                "ios/styles/H5Style.mm",
                "ios/styles/H6Style.mm",
                "ios/styles/HeadingStyleBase.mm",
                "ios/styles/ImageStyle.mm",
                "ios/styles/InlineCodeStyle.mm",
                "ios/styles/ItalicStyle.mm",
                "ios/styles/LinkStyle.mm",
                "ios/styles/MentionStyle.mm",
                "ios/styles/OrderedListStyle.mm",
                "ios/styles/StrikethroughStyle.mm",
                "ios/styles/UnderlineStyle.mm",
                "ios/styles/UnorderedListStyle.mm",
                "ios/textHtmlParser/TextHtmlParser.h",
                "ios/textHtmlParser/TextHtmlParser.mm",
                "ios/utils/AlignmentUtils.h",
                "ios/utils/AlignmentUtils.mm",
                "ios/utils/AttachmentLayoutUtils.h",
                "ios/utils/AttachmentLayoutUtils.mm",
                "ios/utils/CheckboxHitTestUtils.h",
                "ios/utils/CheckboxHitTestUtils.mm",
                "ios/utils/DotReplacementUtils.h",
                "ios/utils/DotReplacementUtils.mm",
                "ios/utils/EnrichedTextTouchHandler.h",
                "ios/utils/EnrichedTextTouchHandler.mm",
                "ios/utils/KeyboardUtils.h",
                "ios/utils/KeyboardUtils.mm",
                "ios/utils/OccurenceUtils.h",
                "ios/utils/OccurenceUtils.mm",
                "ios/utils/ParagraphAttributesUtils.h",
                "ios/utils/ParagraphAttributesUtils.mm",
                "ios/utils/RangeUtils.h",
                "ios/utils/RangeUtils.mm",
                "ios/utils/ShortcutsUtils.h",
                "ios/utils/ShortcutsUtils.mm",
                "ios/utils/StyleUtils.h",
                "ios/utils/StyleUtils.mm",
                "ios/utils/TextBlockTapGestureRecognizer.h",
                "ios/utils/TextBlockTapGestureRecognizer.mm",
                "ios/utils/TextInsertionUtils.h",
                "ios/utils/TextInsertionUtils.mm",
                "ios/utils/TextListsUtils.h",
                "ios/utils/TextListsUtils.mm",
                "ios/utils/WeakBox.h",
                "ios/utils/WeakBox.m",
                "ios/utils/WordsUtils.h",
                "ios/utils/WordsUtils.mm",
                "ios/utils/ZeroWidthSpaceUtils.h",
                "ios/utils/ZeroWidthSpaceUtils.mm",
            ],
            publicHeadersPath: "ios",
            cSettings: [.headerSearchPath("cpp/GumboParser"), .headerSearchPath("cpp/parser"), .headerSearchPath("ios"), .headerSearchPath("ios/config"), .headerSearchPath("ios/enrichedInputTextView"), .headerSearchPath("ios/enrichedTextTextView"), .headerSearchPath("ios/extensions"), .headerSearchPath("ios/generated/ReactCodegen/ReactNativeEnrichedSpec"), .headerSearchPath("ios/htmlParser"), .headerSearchPath("ios/inputAttributesManager"), .headerSearchPath("ios/inputHtmlParser"), .headerSearchPath("ios/interfaces"), .headerSearchPath("ios/internals"), .headerSearchPath("ios/textHtmlParser"), .headerSearchPath("ios/utils"), .headerSearchPath("."), .unsafeFlags(["-include", "react-native-spm-prefix.h"])],
            cxxSettings: [.headerSearchPath("cpp/GumboParser"), .headerSearchPath("cpp/parser"), .headerSearchPath("ios"), .headerSearchPath("ios/config"), .headerSearchPath("ios/enrichedInputTextView"), .headerSearchPath("ios/enrichedTextTextView"), .headerSearchPath("ios/extensions"), .headerSearchPath("ios/generated/ReactCodegen/ReactNativeEnrichedSpec"), .headerSearchPath("ios/htmlParser"), .headerSearchPath("ios/inputAttributesManager"), .headerSearchPath("ios/inputHtmlParser"), .headerSearchPath("ios/interfaces"), .headerSearchPath("ios/internals"), .headerSearchPath("ios/textHtmlParser"), .headerSearchPath("ios/utils"), .headerSearchPath("."), .unsafeFlags(["-include", "react-native-spm-prefix.h"]), .define("DEBUG", .when(configuration: .debug)), .define("NDEBUG", .when(configuration: .release))],
            linkerSettings: [.linkedFramework("UIKit"), .linkedFramework("Foundation"), .linkedFramework("CoreGraphics")]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
